services:
  web:
    build: nginx
    ports:
    - "8080:8080"
  django:
    build: django
    volumes:
    - ./django:/app
    working_dir: /app/app/
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    